name: Build ESurfingDialer with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'zulu'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v4
        with:
          name: ESurfingDialer-artifact
          path: build/libs/
