name: Build ESurfingDialer for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有足够的权限上传 Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext zlib1g-dev swig unzip python3 python3-setuptools

      - name: Set up OpenWrt SDK
        run: |
          cd sdk
          chmod +x ./scripts/feeds  # 添加执行权限
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build ESurfingDialer
        run: |
          cd sdk
          cp -r ../ESurfingDialer package/
          make package/ESurfingDialer/compile V=s

      - name: Debug - List files
        run: |
          ls -R sdk/bin/packages

      - name: Upload IPK file
        uses: actions/upload-artifact@v4
        with:
          name: esurfingdialer.ipk
          path: sdk/bin/packages/ramips/mt7621/esurfingdialer_*.ipk
