name: Build ESurfingDialer for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有足够的权限上传 Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext zlib1g-dev swig unzip python3 python3-setuptools python3-venv

      - name: Manually install python3-distutils
        run: |
          # 获取当前 Python 版本
          PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")

          # 下载 Python 源码
          wget https://www.python.org/ftp/python/${PYTHON_VERSION}.0/Python-${PYTHON_VERSION}.0.tgz

          # 解压源码
          tar -xzf Python-${PYTHON_VERSION}.0.tgz
          cd Python-${PYTHON_VERSION}.0

          # 生成 setup.py
          ./configure
          make

          # 检查 setup.py 是否存在
          if [ -f "setup.py" ]; then
            echo "setup.py found, installing distutils..."
            sudo python3 setup.py install --prefix=/usr
          else
            echo "setup.py not found! Directory contents:"
            ls -l
            exit 1
          fi

          # 清理临时文件
          cd ..
          rm -rf Python-${PYTHON_VERSION}.0 Python-${PYTHON_VERSION}.0.tgz

      - name: Set up OpenWrt SDK
        run: |
          cd sdk
          chmod +x ./scripts/config.guess  # 添加执行权限
          chmod +x ./scripts/feeds  # 确保 feeds 脚本也有执行权限
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build ESurfingDialer
        run: |
          cd sdk
          cp -r ../ESurfingDialer package/
          make package/ESurfingDialer/compile V=s FORCE=1

      - name: Debug - List files
        run: |
          ls -R sdk/bin/packages

      - name: Upload IPK file
        uses: actions/upload-artifact@v4
        with:
          name: esurfingdialer.ipk
          path: sdk/bin/packages/ramips/mt7621/esurfingdialer_*.ipk
